spring:
  application:
    name: spring-rag-engine
  logging:
    level:
      org.springframework.boot.context.config: DEBUG
  ai:
    ollama:
      base-url: http://localhost:11434
      embedding:
        options:
          model: nomic-embed-text
  datasource:
    url: jdbc:postgresql://localhost:5432/vector
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

rag:
  chunking-config:
    chunk-size: 200
    keep-separator: true
    min-chunk-size: 20
    max-num-chunk-size: 25
