spring:
  application:
    name: spring-rag-engine
  ai:
    ollama:
      base-url: http://localhost:11434
      embedding:
        options:
          model: nomic-embed-text
rag:
  chunking-config:
    size: 600
    overlap: 50
    keepSeparator: true
    minChunkSize: 10
    maxNumChunks: 100
